export const services = [
  {
    id: 1,
    title: "Web Development",
    description: "Fast, scalable websites and web apps built with modern technologies.",
    icon: "Code",
    fullDescription:
      "We create modern, responsive websites and web applications using the latest technologies like React, Next.js, and Node.js. Our solutions are optimized for performance, SEO, and user experience.",
    features: [
      "Responsive Design",
      "SEO Optimization",
      "Performance Optimization",
      "Modern Frameworks",
      "Database Integration",
    ],
    startingPrice: 500,
  },
  {
    id: 2,
    title: "App Development",
    description: "Cross-platform mobile apps that users love and businesses need.",
    icon: "Smartphone",
    fullDescription:
      "Build native and cross-platform mobile applications for iOS and Android. We use React Native and Flutter to deliver high-quality apps that work seamlessly across all devices.",
    features: [
      "Cross-platform Development",
      "Native Performance",
      "App Store Deployment",
      "Push Notifications",
      "Offline Functionality",
    ],
    startingPrice: 800,
  },
  {
    id: 3,
    title: "SEO Services",
    description: "Technical audits, on-page optimization, and growth content strategy.",
    icon: "Search",
    fullDescription:
      "Comprehensive SEO services including technical audits, keyword research, on-page optimization, and content strategy to improve your search engine rankings and organic traffic.",
    features: [
      "Technical SEO Audit",
      "Keyword Research",
      "On-page Optimization",
      "Content Strategy",
      "Performance Tracking",
    ],
    startingPrice: 300,
  },
  {
    id: 4,
    title: "Graphic Design",
    description: "Brand-ready visuals and marketing assets that convert.",
    icon: "Palette",
    fullDescription:
      "Professional graphic design services for branding, marketing materials, web graphics, and print design. We create visually stunning designs that align with your brand identity.",
    features: ["Brand Identity", "Marketing Materials", "Web Graphics", "Print Design", "Logo Design"],
    startingPrice: 200,
  },
  {
    id: 5,
    title: "Digital Marketing",
    description: "Data-driven campaigns that grow your business and reach.",
    icon: "TrendingUp",
    fullDescription:
      "Strategic digital marketing campaigns across social media, email, and paid advertising platforms. We focus on ROI-driven strategies that generate real business results.",
    features: [
      "Social Media Marketing",
      "Email Campaigns",
      "PPC Advertising",
      "Analytics & Reporting",
      "Conversion Optimization",
    ],
    startingPrice: 400,
  },
  {
    id: 6,
    title: "Brand Strategy",
    description: "Complete brand development and positioning strategies.",
    icon: "Target",
    fullDescription:
      "Develop comprehensive brand strategies that differentiate your business in the market. From brand positioning to visual identity, we help you build a strong brand presence.",
    features: ["Brand Positioning", "Visual Identity", "Brand Guidelines", "Market Research", "Competitive Analysis"],
    startingPrice: 600,
  },
]

export const consultationService = {
  title: "Personal Consultation",
  description: "1:1 expert advice on your project or learning journey",
  hourlyRate: 20,
  features: [
    "Personalized mentorship sessions",
    "Project guidance and code review",
    "Career advice and planning",
    "Technical problem solving",
    "Learning path recommendations",
    "Portfolio review and feedback",
  ],
  availableTopics: [
    "Web Development",
    "App Development",
    "SEO Strategy",
    "Digital Marketing",
    "Career Guidance",
    "Project Planning",
  ],
}

export const featuredCourses = [
  {
    id: 1,
    title: "Web Dev Bootcamp",
    level: "Beginner",
    duration: "8 weeks",
    price: 49,
    rating: 4.9,
    students: 1250,
    nextCohort: "2024-02-15",
    liveOnZoom: true,
    category: "Web Development",
    instructor: "John Smith",
    description: "Complete web development bootcamp covering HTML, CSS, JavaScript, React, and Node.js",
  },
  {
    id: 2,
    title: "React & Next.js Mastery",
    level: "Intermediate",
    duration: "6 weeks",
    price: 35,
    rating: 4.8,
    students: 890,
    nextCohort: "2024-02-20",
    liveOnZoom: true,
    category: "Web Development",
    instructor: "Sarah Johnson",
    description: "Advanced React concepts and Next.js framework for building modern web applications",
  },
  {
    id: 3,
    title: "SEO Fundamentals",
    level: "Beginner",
    duration: "4 weeks",
    price: 15,
    rating: 4.7,
    students: 2100,
    nextCohort: "2024-02-10",
    liveOnZoom: true,
    category: "Digital Marketing",
    instructor: "Mike Chen",
    description: "Learn the fundamentals of SEO including keyword research, on-page optimization, and analytics",
  },
  {
    id: 4,
    title: "Digital Marketing 101",
    level: "Beginner",
    duration: "3 weeks",
    price: 2,
    rating: 4.6,
    students: 3500,
    nextCohort: "2024-02-05",
    liveOnZoom: true,
    category: "Digital Marketing",
    instructor: "Emily Rodriguez",
    description: "Introduction to digital marketing including social media, email marketing, and PPC advertising",
  },
  {
    id: 5,
    title: "Mobile App Development",
    level: "Intermediate",
    duration: "10 weeks",
    price: 65,
    rating: 4.9,
    students: 750,
    nextCohort: "2024-02-25",
    liveOnZoom: true,
    category: "App Development",
    instructor: "David Kim",
    description: "Build cross-platform mobile apps using React Native and Flutter",
  },
  {
    id: 6,
    title: "UI/UX Design Principles",
    level: "Beginner",
    duration: "5 weeks",
    price: 25,
    rating: 4.8,
    students: 1800,
    nextCohort: "2024-02-12",
    liveOnZoom: true,
    category: "Design",
    instructor: "Lisa Wang",
    description: "Learn design principles, user research, wireframing, and prototyping",
  },
]

export const allCourses = [
  ...featuredCourses,
  {
    id: 7,
    title: "Advanced JavaScript",
    level: "Advanced",
    duration: "6 weeks",
    price: 40,
    rating: 4.7,
    students: 650,
    nextCohort: "2024-03-01",
    liveOnZoom: true,
    category: "Web Development",
    instructor: "Alex Thompson",
    description: "Deep dive into advanced JavaScript concepts, ES6+, and modern development patterns",
  },
  {
    id: 8,
    title: "Python for Beginners",
    level: "Beginner",
    duration: "4 weeks",
    price: 20,
    rating: 4.6,
    students: 2200,
    nextCohort: "2024-02-18",
    liveOnZoom: true,
    category: "Programming",
    instructor: "Maria Garcia",
    description: "Learn Python programming from scratch with hands-on projects and exercises",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Sarah Johnson",
    role: "Frontend Developer",
    company: "TechCorp",
    content:
      "The live Zoom classes made all the difference. Having real-time interaction with instructors helped me land my dream job.",
    avatar: "/placeholder.svg?height=60&width=60",
    rating: 5,
  },
  {
    id: 2,
    name: "Michael Chen",
    role: "Digital Marketer",
    company: "Growth Agency",
    content:
      "Starting at just $2, I could test the waters. The quality exceeded my expectations and I upgraded to the full program.",
    avatar: "/placeholder.svg?height=60&width=60",
    rating: 5,
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    role: "Freelance Designer",
    company: "Self-employed",
    content:
      "The consultation service was a game-changer. Personal mentorship helped me scale my freelance business significantly.",
    avatar: "/placeholder.svg?height=60&width=60",
    rating: 5,
  },
]

export const trustedLogos = [
  { name: "Google", logo: "/placeholder.svg?height=40&width=120" },
  { name: "Microsoft", logo: "/placeholder.svg?height=40&width=120" },
  { name: "Amazon", logo: "/placeholder.svg?height=40&width=120" },
  { name: "Meta", logo: "/placeholder.svg?height=40&width=120" },
  { name: "Netflix", logo: "/placeholder.svg?height=40&width=120" },
]

export const pricingPlans = [
  {
    id: 1,
    name: "Basic",
    description: "Perfect for getting started with your learning journey",
    price: 2,
    icon: "BookOpen",
        courseId: 4, // 👈 Digital Marketing 101 ka id (allCourses se)

    popular: false,
    features: [
      "1 intro Zoom class",
      "Q&A session with instructor",
      "Class recording access",
      "Community forum access",
      "Basic project template",
      "Email support",
    ],
    buttonText: "Get Started",
  },
  {
    id: 2,
    name: "Standard",
    description: "Ideal for serious learners who want comprehensive training",
    price: 15,
    icon: "Zap",
    popular: true,
        courseId: 3, // 👈 Digital Marketing 101 ka id (allCourses se)

    features: [
      "3 live Zoom classes",
      "Mini project with feedback",
      "1-on-1 feedback session",
      "Certificate of completion",
      "Lifetime recording access",
      "Priority community support",
      "Resource library access",
    ],
    buttonText: "Most Popular",
  },
  {
    id: 3,
    name: "Premium",
    description: "Complete program with personalized mentorship and career guidance",
    price: 49,
    icon: "Crown",
        courseId: 1, // 👈 Digital Marketing 101 ka id (allCourses se)

    popular: false,
    features: [
      "Full cohort (6-8 weeks) on Zoom",
      "1:1 mentor call (30 minutes)",
      "Capstone project review",
      "Career guidance session",
      "Portfolio review & feedback",
      "Job referral assistance",
      "Lifetime community access",
      "All previous plan benefits",
    ],
    buttonText: "Go Premium",
  },
]
